[package]
name = "swww_itch_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.98" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = { version = "2.0.12" }
tokio = { version = "1.46.1", features = ["full"] }
