[workspace]
members = ["src-itchd", "src-itch-shared"]
resolver = "3"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
# tokio = { version = "1", features = ["full", "tracing"] }
anyhow = "1.0.98"
